### ISSUE TITLE
Test pattern generation failed: No max Value found, all values are null!

### ISSUE THREAD

**Issue by Disane87** [garethky/PrusaSlicerPressureAdvanceCalibration#14]
Hi! I just saw your tool and i want to use it. Followed your instruction but the tool gives me this error:
![image](https://github.com/garethky/PrusaSlicerPressureAdvanceCalibration/assets/956158/896acaa5-bced-43a8-b00e-0d219eb7669b)

What is the problem and how can I solve this?

Used gcode:
[prusa-slicer-pressure-advance-test_7m_0,20mm_210C_PLA+_ENDER3S1.zip](https://github.com/garethky/PrusaSlicerPressureAdvanceCalibration/files/14075886/prusa-slicer-pressure-advance-test_7m_0.20mm_210C_PLA%2B_ENDER3S1.zip)

**Comment by garethky** [comment]
All of your accelerations are set to 0. The code doesn't correctly fall back to the default_acceleration in 2 cases. So I fixed that. Now it shows that it got 500 from the default_acceleration:

![Screenshot 2024-01-28 at 1 23 28 PM](https://github.com/garethky/PrusaSlicerPressureAdvanceCalibration/assets/339834/d632be3d-df40-4fed-8b98-60f3fc7bcc82)

You are going to run into another problem. You're running klipper and your start gcode has variables in it that are not on the short list of whats supported for klipper. See: https://github.com/garethky/PrusaSlicerPressureAdvanceCalibration/blob/427cffe9fe4fa70b5eccc54cc61b183668a0f5d9/src/lib/StartEndGcodePrep.ts#L64
I think you could just delete the comments in the start gocde template for now and it would work. Getting support for every last variable needs to be its own issue. Some variables might not be something I can calculate so bulk copying them out of the file wasn't an option. (e.g. the layer counts wont be the same, I don't have a calculation for print time etc.)
