### ISSUE TITLE
Invalid value for zhop instruction

### ISSUE THREAD

**Issue by mayty** [garethky/PrusaSlicerPressureAdvanceCalibration#16]
Zhop instruction needs to be `G1 Z{layer_height + z_hop}`.
When I ran the generated code with layer height 0.4mm and zhop 0.25mm nozzle ran through printed layers (see attached image)
![photo_2024-02-29_00-54-11](https://github.com/garethky/PrusaSlicerPressureAdvanceCalibration/assets/45905278/d3fbd16e-20eb-4501-8994-7199e803c804)

**Comment by garethky** [comment]
Yes, the z-hop height isn't being added to the layer height.

**Comment by garethky** [comment]
There were cases where it never went back down to the regular z height. There were also many places where there were long travel moves happened with no z hop.

@mayty please try out the new version and see if this fixes your issue.

**Comment by mayty** [comment]
@garethky 
It works like a charm, thanks
