### ISSUE TITLE
Wrong gcode generated for the Mk3.9s

### ISSUE THREAD

**Issue by VorpalBlade** [garethky/PrusaSlicerPressureAdvanceCalibration#21]
Prusa Mk3.9s uses M572, but the website decides it should use M900 when I upload to it. This is wrong. Attached is the .bgcode file I uploaded, and the gcode file I got back

[gcodes.zip](https://github.com/user-attachments/files/17166714/gcodes.zip)

**Comment by garethky** [comment]
Fix incoming

**Comment by garethky** [comment]
Fix deployed, please give it a test

**Comment by mkar1984** [comment]
Tested on MK3.5 and MK4S: works
